name: Build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: MillieSilva/RT-DeskLib
        ref: main
        ssh-key: ${{ secrets.DESKLIB_KEY }}

    - uses: actions/checkout@v3
      with:
        repository: MillieSIlva/RT-Watcher
        ref: main
        path: Watcher
    
    - name: Go to Watcher directory
      run: cd Watcher
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        dotnet nuget locals all --clear
        dotnet restore
    
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
