name: Build

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    strategy:
      matrix:
        architecture: [win-x64, linux-x64]

    runs-on: windows-latest

    env:
      Solution_Name: Watcher.sln

    steps:
    - uses: actions/checkout@v3
      with:
        repository: MillieSilva/RT-DeskLib
        ref: main
        ssh-key: ${{ secrets.DESKLIB_KEY }}
        path: Library

    - uses: actions/checkout@v3
      with:
        repository: MillieSilva/RT-Watcher
        ref: main
        path: Watcher

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      working-directory: ./Watcher
      run: dotnet restore

    - name: Build Publish
      working-directory: ./Watcher
      run: dotnet publish -c Release -r ${{ matrix.architecture }} --self-contained=true -p:UseAppHost=true -p:PublishSingleFile=true
      #-p:PublishReadyToRun=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.architecture }} Release
        path: .\Watcher\bin\Release\net6.0\${{ matrix.architecture }}\publish


